services:
  - type: web
    name: property-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DB_TYPE
        value: firebase
      - key: PORT
        value: 3000
      - key: FIREBASE_PROJECT_ID
        value: property-backend-12169
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false

# Remove the databases section since we're using mock service for now
# databases:
#   - name: property-db
#     databaseName: property_management
#     user: property_user 